[platformio]
default_envs = basic

[env]
platform = espressif32@6.5.0
framework = arduino
monitor_speed = 115200
board_build.embed_files = data/ui_font.vlw
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DWM_NODEBUG
lib_deps =
  m5stack/M5Unified@0.2.7
  m5stack/M5GFX@0.2.29
  tzapu/WiFiManager@2.0.17
  bblanchon/ArduinoJson@6.21.5

[env:core2]
board = m5stack-core2

[env:basic]
board = m5stack-core-esp32
